spring.application.name=talentmatchpro

server.port=${PORT:8080}

# H2 Database
spring.datasource.url=jdbc:h2:mem:talentmatchdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update


# =========================================================
# Spring AI - Groq
# =========================================================

spring.ai.openai.api-key=${GROQ_API_KEY}

spring.ai.openai.base-url=https://api.groq.com/openai

spring.ai.openai.chat.options.model=openai/gpt-oss-20b